export const eventStatusOptions = ["Open", "Closed"];

export const eventCategoryOptions = [
  "Social Event",
  "Sports",
  "Technology Event",
];

export const dashboardEvents = [
  {
    id: "evt-d1",
    title: "Tech Session and design",
    category: "Technology Event",
    status: "Open",
    startDate: "2026-01-01T06:00:00",
    endDate: "2026-01-01T18:00:00",
    duration: "12 hours",
    maxAttendee: 200,
    address: "Toul Kork, Phnom Penh City, Cambodia",
    description: "Explore breakthroughs in science and technology with expert speakers.",
    image: "/images/presentation.png",
    isPublic: true,
  },
  {
    id: "evt-d2",
    title: "Products Con",
    category: "Technology Event",
    status: "Closed",
    startDate: "2026-01-01T09:00:00",
    endDate: "2026-01-01T17:00:00",
    duration: "8 hours",
    maxAttendee: 350,
    address: "Toul Kork, Phnom Penh City, Cambodia",
    description: "Product launches, demos, and networking for innovators.",
    image: "/images/festival.png",
    isPublic: true,
  },
  {
    id: "evt-d3",
    title: "Science Hub",
    category: "Technology Event",
    status: "Open",
    startDate: "2026-01-01T10:00:00",
    endDate: "2026-01-01T16:00:00",
    duration: "6 hours",
    maxAttendee: 180,
    address: "Chamkarmon, Phnom Penh City, Cambodia",
    description: "Hands-on science demos and talks for students and professionals.",
    image: "/images/presentation.png",
    isPublic: true,
  },
  {
    id: "evt-d4",
    title: "Summer Music Festival",
    category: "Social Event",
    status: "Open",
    startDate: "2026-02-14T18:00:00",
    endDate: "2026-02-15T02:00:00",
    duration: "8 hours",
    maxAttendee: 500,
    address: "Central Park, New York",
    description: "Live bands, food trucks, and fireworks under the stars.",
    image: "/images/campfire.png",
    isPublic: true,
  },
  {
    id: "evt-d5",
    title: "Design Skill Workshop",
    category: "Technology Event",
    status: "Closed",
    startDate: "2026-01-08T10:00:00",
    endDate: "2026-01-08T16:00:00",
    duration: "6 hours",
    maxAttendee: 80,
    address: "Toul Kork, Phnom Penh City, Cambodia",
    description: "Hands-on design sessions for UI and product teams.",
    image: "/images/presentation.png",
    isPublic: true,
  },
  {
    id: "evt-d6",
    title: "Grand Prix Weekend",
    category: "Sports",
    status: "Open",
    startDate: "2026-04-05T08:00:00",
    endDate: "2026-04-06T20:00:00",
    duration: "2 days",
    maxAttendee: 1000,
    address: "Sepang International Circuit, Malaysia",
    description: "High-speed action on the track with pit tours and fan zones.",
    image: "/images/racecar.png",
    isPublic: true,
  },
];
