export const members = [
  {
    id: "001",
    name: "Thomas Brown",
    avatar: "/images/Ellipse 44.png",
    gender: "Male",
    email: "ThomasNikola@gmail.com",
    address: "742 Evergreen Terrace, Springfield",
    role: "Admin",
  },
  {
    id: "002",
    name: "Sarah Johnson",
    avatar: null,
    gender: "Female",
    email: "sarah.johnson@gmail.com",
    address: "128 Oak Street, Portland",
    role: "User",
  },
  {
    id: "003",
    name: "Michael Chen",
    avatar: null,
    gender: "Male",
    email: "michael.chen@gmail.com",
    address: "456 Maple Avenue, Seattle",
    role: "Sub admin",
  },
  {
    id: "004",
    name: "Emily Davis",
    avatar: null,
    gender: "Female",
    email: "emily.davis@gmail.com",
    address: "89 Pine Road, Austin",
    role: "User",
  },
  {
    id: "005",
    name: "James Wilson",
    avatar: null,
    gender: "Male",
    email: "james.wilson@gmail.com",
    address: "321 Cedar Lane, Denver",
    role: "Sub admin",
  },
  {
    id: "006",
    name: "Olivia Martinez",
    avatar: null,
    gender: "Female",
    email: "olivia.martinez@gmail.com",
    address: "567 Birch Blvd, Miami",
    role: "User",
  },
  {
    id: "007",
    name: "Daniel Lee",
    avatar: null,
    gender: "Male",
    email: "daniel.lee@gmail.com",
    address: "901 Willow Way, Chicago",
    role: "User",
  },
  {
    id: "008",
    name: "Sophia Taylor",
    avatar: null,
    gender: "Female",
    email: "sophia.taylor@gmail.com",
    address: "234 Elm Court, Boston",
    role: "Sub admin",
  },
  {
    id: "009",
    name: "William Anderson",
    avatar: null,
    gender: "Male",
    email: "william.anderson@gmail.com",
    address: "678 Ash Drive, Phoenix",
    role: "User",
  },
  {
    id: "010",
    name: "Ava Thomas",
    avatar: null,
    gender: "Female",
    email: "ava.thomas@gmail.com",
    address: "345 Spruce Street, Dallas",
    role: "User",
  },
  {
    id: "011",
    name: "Ethan Jackson",
    avatar: null,
    gender: "Male",
    email: "ethan.jackson@gmail.com",
    address: "789 Poplar Place, San Diego",
    role: "Sub admin",
  },
  {
    id: "012",
    name: "Isabella White",
    avatar: null,
    gender: "Female",
    email: "isabella.white@gmail.com",
    address: "112 Hickory Hill, Nashville",
    role: "User",
  },
  {
    id: "013",
    name: "Noah Harris",
    avatar: null,
    gender: "Male",
    email: "noah.harris@gmail.com",
    address: "456 Sycamore Ave, Atlanta",
    role: "User",
  },
  {
    id: "014",
    name: "Mia Clark",
    avatar: null,
    gender: "Female",
    email: "mia.clark@gmail.com",
    address: "890 Walnut Street, Detroit",
    role: "User",
  },
];

export const MEMBERS_PAGE_SIZE = 7;
