export const initialNotifications = [
  {
    id: "n1",
    name: "Ly Nita",
    avatar: "/images/Ellipse 44.png",
    avatarBg: "#dbeafe",
    time: "Last Wednesday at 9:42 AM",
    unread: true,
    href: "/dashboard/user-request",
  },
  {
    id: "n2",
    name: "Morng many",
    avatar: null,
    avatarBg: "#ede9fe",
    time: "Last Wednesday at 9:42 AM",
    unread: false,
    href: "/dashboard/user-request",
  },
  {
    id: "n3",
    name: "Serey both",
    avatar: null,
    avatarBg: "#dcfce7",
    time: "Last Wednesday at 9:42 AM",
    unread: true,
    href: "/dashboard/user-request",
  },
  {
    id: "n4",
    name: "Chantha lim",
    avatar: null,
    avatarBg: "#fef9c3",
    time: "Last Wednesday at 9:42 AM",
    unread: false,
    href: "/dashboard/user-request",
  },
  {
    id: "n5",
    name: "Dara pich",
    avatar: null,
    avatarBg: "#ffedd5",
    time: "Last Wednesday at 9:42 AM",
    unread: true,
    href: "/dashboard/user-request",
  },
  {
    id: "n6",
    name: "Sophea keo",
    avatar: null,
    avatarBg: "#e0e7ff",
    time: "Last Wednesday at 9:42 AM",
    unread: false,
    href: "/dashboard/user-request",
  },
];
