export const USER_REQUEST_PAGE_SIZE = 7;

export const userRequests = [
  {
    id: "001",
    name: "Ly Nita",
    avatar: "/images/Ellipse 44.png",
    gender: "Female",
    email: "nita2024@gmail.com",
    address: "Street156, Sen Sok, Phnom Penh",
    phone: "012345678",
  },
  {
    id: "002",
    name: "Morng many",
    avatar: null,
    gender: "Female",
    email: "many34@gmail.com",
    address: "Phnom Penh",
    phone: "092356789",
  },
  {
    id: "003",
    name: "Serey both",
    avatar: null,
    gender: "Male",
    email: "both@gmail.com",
    address: "Kampong Cham",
    phone: "0974567863",
  },
  {
    id: "004",
    name: "Chantha lim",
    avatar: null,
    gender: "Female",
    email: "lim.chantha@gmail.com",
    address: "Siem Reap",
    phone: "0887654321",
  },
  {
    id: "005",
    name: "Dara pich",
    avatar: null,
    gender: "Male",
    email: "dara.pich@gmail.com",
    address: "Battambang",
    phone: "0961234567",
  },
  {
    id: "006",
    name: "Sophea keo",
    avatar: null,
    gender: "Female",
    email: "sophea.k@gmail.com",
    address: "Phnom Penh",
    phone: "0934567890",
  },
  {
    id: "007",
    name: "Vuthy san",
    avatar: null,
    gender: "Male",
    email: "vuthy.san@gmail.com",
    address: "Kandal",
    phone: "0987654321",
  },
  {
    id: "008",
    name: "Rina chea",
    avatar: null,
    gender: "Female",
    email: "rina.chea@gmail.com",
    address: "Preah Sihanouk",
    phone: "0912345678",
  },
  {
    id: "009",
    name: "Bopha sun",
    avatar: null,
    gender: "Female",
    email: "bopha.sun@gmail.com",
    address: "Takeo",
    phone: "0901122334",
  },
  {
    id: "010",
    name: "Heng mao",
    avatar: null,
    gender: "Male",
    email: "heng.mao@gmail.com",
    address: "Kampot",
    phone: "0978877665",
  },
  {
    id: "011",
    name: "Nary te",
    avatar: null,
    gender: "Female",
    email: "nary.te@gmail.com",
    address: "Phnom Penh",
    phone: "0923344556",
  },
  {
    id: "012",
    name: "Pisach ly",
    avatar: null,
    gender: "Male",
    email: "pisach.ly@gmail.com",
    address: "Pursat",
    phone: "0967788990",
  },
  {
    id: "013",
    name: "Kunthea om",
    avatar: null,
    gender: "Female",
    email: "kunthea.om@gmail.com",
    address: "Kampong Speu",
    phone: "0889900112",
  },
  {
    id: "014",
    name: "Sokha penh",
    avatar: null,
    gender: "Male",
    email: "sokha.penh@gmail.com",
    address: "Phnom Penh",
    phone: "0932211445",
  },
];
